# Generated by Django 4.0.3 on 2022-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('lot_number', models.IntegerField(max_length=300)),
                ('exp_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
