# Generated by Django 4.0.3 on 2022-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='lot_number',
            field=models.IntegerField(),
        ),
    ]
