# Generated by Django 4.0.3 on 2022-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_manager_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
