# Generated by Django 4.0.3 on 2022-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_item_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lot_number',
            field=models.BigIntegerField(),
        ),
    ]
