# Generated by Django 4.0.3 on 2022-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_item_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lot_number',
            field=models.CharField(max_length=50),
        ),
    ]
