# Generated by Django 4.0.1 on 2022-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
