# Generated by Django 4.0.1 on 2022-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
